### ISSUE TITLE
default.jpg not loading because of a mangled URL

### ISSUE THREAD

**Issue by martini1992** [SamTV12345/PodFetch#51]
### Describe the bug

default.jpg is unable to load because of a mangled URL.

Expected:
http://example.com:8000/ui/default.jpg

Actual:
http://example.com:8000/http://localhost/ui/default.jpg

I'm using this podcast (if you don't know one that doesn't serve a suitable image) it has images in it but not in the correct format to be used (itunes tags)

### Reproduction

Try to load the podcast list, or any page which would show the default image

### System Info

```Shell
I use the docker image on my server and access the instance using machine name and port.  
relevant docker compose environment variable:
SERVER_URL=http://example.com:8000
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Hi @martini1992,

thank you for creating an issue. I am trying to reproduce the issue. Did you forget to include the podcast name you tried to download?

**Comment by martini1992** [comment]
Yeah, thought I'd pasted it in but here you go:
https://feeds.fireside.fm/selfhosted/rss

**Comment by SamTV12345** [comment]
Thanks. How did you add the podcast. Via iTunes worked without a problem and the podcast also has a podcast image (Rocket with the text Selfhosted)

**Comment by martini1992** [comment]
I added it from a OPML file from the default RSS feed I posted.

**Comment by SamTV12345** [comment]
Do you use the AMD64 images? If yes it should be resolved. But you need to delete the faulty data from the database. Therefore download sqlite from your package manager. Do sqlite podcast.db and paste in the following lines

```sql
DELETE FROM podcast_episodes WHERE podcast_id=(SELECT id FROM podcasts WHERE rssfeed='https://feeds.fireside.fm/selfhosted/rss');
DELETE FROM podcasts WHERE rssfeed='https://feeds.fireside.fm/selfhosted/rss';

```

**Comment by martini1992** [comment]
Hmm, the image is still missing, though now it's trying http://example.com:8000/podcasts/931252065/image.jpg, which is returning 200 OK but Firefox says the "image cannot be displayed because it contains errors".

**Comment by SamTV12345** [comment]
I tried this opml file: 

<opml version="1.0">
	<head>
		<title>Sample OPML file for RSSReader</title>
	</head>
	<body>
		<outline title="News" text="News">
			<outline text="Big News Finland" title="Big News Finland" type="rss" xmlUrl="https://feeds.fireside.fm/selfhosted/rss"/>
		</outline>
		</body>
	</opml>

That worked with an empty database.

**Comment by SamTV12345** [comment]
Did you pull again from latest?

**Comment by martini1992** [comment]
Yeah, I killed the container and deleted the cached image, then deleted all data (start from scratch) and uploaded the OPML file which is functionally the same as yours, though I have multiple outlines for a few podcasts.

**Comment by SamTV12345** [comment]
Should be working now. Two issues were present. The first was the wrong url which I fixed the other one was that I never copy the image to the docker build. That is why no image was ever shown after you tried it.

**Comment by martini1992** [comment]
Cheers, I'll check tomorrow :)

**Comment by SamTV12345** [comment]
Sure no problem. If it still persist just reopen the issue. I'm always happy if I get feedback from users. 😀

**Comment by martini1992** [comment]
Awesome, it's working fine now, thanks!
